theme = "rose_pine_dawn"

[editor]
true-color = true
color-modes = true
rulers = [ 80, 100, 120 ]
text-width = 100
bufferline = "multiple"
cursorline = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"

[editor.indent-guides]
render = true

[keys.normal.space]
q = ":reflow"

[keys.normal.space.x]
l = ":sh hx-link-sel %{buffer_name} %{selection_line_start} %{selection_line_end}"
b = ":sh hx-blame %{buffer_name}"
