theme = "catppuccin_latte"

[editor]
true-color = true
color-modes = true
rulers = [ 80, 100, 120 ]
text-width = 100
bufferline = "multiple"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"

[editor.indent-guides]
render = true

[keys.normal]
"space" = { q = ":reflow" }