[[language]]
name = "email"
scope = "text.email"
file-types = ["eml", "mbox"]
roots = []
indent = { tab-width = 4, unit = "    " }
comment-token = ">"
rulers = [72]
auto-format = false

[[language]]
name = "starlark"
file-types = ["bzl", "bazel", "BUILD", "star"]

# BEGIN: Prettier formatter config + eslint as an LSP
# Sources:
# * prettier: https://github.com/helix-editor/helix/wiki/External-formatter-configuration#prettier
# * eslint: https://docs.helix-editor.com/languages.html#configuring-language-servers-for-a-language
[[language]]
name = "html"
formatter = { command = "prettier", args = [ "--parser", "html" ] }

[[language]]
name = "json"
formatter = { command = "prettier", args = [ "--parser", "json" ] }

[[language]]
name = "css"
formatter = { command = "prettier", args = [ "--parser", "css" ] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
roots = ["package.json"]
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
roots = ["package.json"]
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
language-servers = [ "typescript-language-server", "vscode-eslint-language-server" ]
auto-format = true
# END: Prettier formatter config

[language-server.typescript-language-server]
command = "vtsls"

[language-server.typescript-language-server.config]
typescript.tsserver.maxTsServerMemory = 8192
typescript.tsserver.log = "terse"
tsserver.useLocalTsdk = true

