[[language]]
name = "email"
scope = "text.email"
file-types = ["eml", "mbox"]
roots = []
indent = { tab-width = 4, unit = "    " }
comment-token = ">"
rulers = [72]
auto-format = false

[[language]]
name = "starlark"
file-types = ["bzl", "bazel", "BUILD", "star"]
