# Replace the "❯" symbol in the prompt with "$"
[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[aws]
disabled = true

# "bold red" style when capacity is between 0% and 10%
[[battery.display]] 
threshold = 10
style = "bold red"
discharging_symbol = "↓!"
charging_symbol = "↑"

# "bold yellow" style when capacity is between 10% and 30%
[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = "↓"
charging_symbol = "↑"

[dotnet]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncate_to_repo = false
format = "in [$path]($style)[$read_only]($read_only_style) "

[gcloud]
symbol = "gcloud "

[git_branch]
symbol = "branch "

[git_status]
disabled = true

[golang]
symbol = "go "

[hg_branch]
disabled = true

[hostname]
ssh_symbol = "on"
format = "$ssh_symbol [$hostname]($style) "

[java]
disabled = true

[nodejs]
symbol = "node "

[package]
disabled = true

[perl]
symbol = "perl "

[python]
symbol = "python "

[ruby]
symbol = "ruby "

[rust]
symbol = "rust "

[shlvl]
symbol = "^"
disabled = false

[swift]
symbol = "swift "

[terraform]
symbol = "tf "

[time]
disabled = false
use_12hr = true
#style = "#ffffff"

[username]
show_always = true
format = "[$user]($style) "

[zig]
symbol = "zig "
